### ISSUE TITLE
Potential copy/paste error on LFO for top modulation

### ISSUE THREAD

**Issue by Blackaddr** [hexeguitar/t40fx#2]
Regarding Line 499 here:
https://github.com/hexeguitar/t40fx/blob/5c966b18dab8f0479b03c6e2602949c5a75c3c8c/Hx_PlateReverb/effect_platervbstereo.cpp#L499

Is this a copy & paste error? Based on the pattern of the previous tap modulations, should this particular line have been lfo2_out_sin instead of lfo2_out_cos to be consistent with line [495](        temp16 = (lp_dly4_idx + lp_dly4_offset_R + (lfo1_out_sin>>LFO_FRAC_BITS)) % (sizeof(lp_dly4_buf)/sizeof(float32_t));)? Or was this intentional?

`input = (float32_t)(lfo2_out_cos & LFO_FRAC_MASK) / ((float32_t)LFO_FRAC_MASK); // interp. k`

**Comment by hexeguitar** [comment]
Good catch, yes copy paste error, but in line 495, channel R, delay line 4 is modulated by lfo2_out_cos. It should be like this:
`temp16 = (lp_dly4_idx + lp_dly4_offset_R + (lfo2_out_cos>>LFO_FRAC_BITS)) % (sizeof(lp_dly4_buf)/sizeof(float32_t));`
Affects also the _F32 version. Fixed. Thanks!

**Comment by Blackaddr** [comment]
@hexeguitar Okay, just to confirm the intent on the LFO modulations. This is what I see in the code now after your fix.
// LEFT CHANNEL.
Delay 1 -> LFO1, cos
Delay 2 -> LFO1, sin
Delay 3 - > LFO2, cos
Delay 4 -> LFO2, sin

// RIGHT CHANNEL
Delay 1 -> LFO 2, cos
Delay 2 -> LFO1, cos
Delay 3 -> LFO2, sin
Delay 4 -> LFO2, cos

I was surprised the R channel is using LFO2 three times, LOF1, and cos three times, sin once. Is this to create more spatial separate versus the L channel with LFO1 twice, a sin and a cos, LFO2 twice, a sin and a cos?

Sorry if I'm being pedantic! I am refactoring a version of this code to try to port the audio arrays to external SRAM and wanted to consolidate some of the copy/paste into reusable functions, but want to make sure I'm preserving your original tonal intent.

**Comment by hexeguitar** [comment]
I am actually not modulating the delay1, personally found it a bit too much of chorusing effect.
`#define TAP1_MODULATED`
is commented out. I left the option in case someone wants to add more modulation.
Delay lines for R & L channels are modulated from the same LFO, but via sin and cos outputs to give the waveforms some phase shift. There is really no special procedure here, feel free to play with different lfo for each delay line.
Following the above, the Delay 1 R should be modulated from LFO1 sin.
